# Apply the compatibility delta to the builder's authenticated UESDK checkout.
find_package(Git REQUIRED)
set(_acr_sdk "${CMAKE_CURRENT_SOURCE_DIR}/dependencies/submodules/UESDK")
set(_acr_patch "${CMAKE_CURRENT_SOURCE_DIR}/patches/UESDK-ACR-compatibility.patch")
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${_acr_sdk}" apply --reverse --check "${_acr_patch}" RESULT_VARIABLE _already OUTPUT_QUIET ERROR_QUIET)
if(NOT _already EQUAL 0)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${_acr_sdk}" apply --check "${_acr_patch}" RESULT_VARIABLE _check ERROR_VARIABLE _error)
    if(NOT _check EQUAL 0)
        message(FATAL_ERROR "ACR SDK compatibility patch does not match this checkout: ${_error}")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${_acr_sdk}" apply "${_acr_patch}" RESULT_VARIABLE _apply)
    if(NOT _apply EQUAL 0)
        message(FATAL_ERROR "Could not apply ACR SDK compatibility patch")
    endif()
endif()
